apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: passitonbooks
manifests:
  rawYaml:
    - ./infra/k8s/*.yaml
build:
  local:
    push: false
  artifacts:
    - image: sonnyboychauke/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: ./
deploy:
  kubectl: {}
